export const levelData = new Map([
  [
    "level1",
    {
      name: "level.1.name",
      isTutorial: !![],
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "1_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [{ x: -22.5, y: 0x39, z: 174.5 }],
      startItems: [],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x0,
      zombieKillPoints: 0xa,
      unlocksPlant: {
        entityId: "bn:sunflower",
        name: "level.1.unlock",
        spawnLocation: { x: -21, y: 0x3a, z: 0xb6 },
        scale: 0x3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 0x3c, z: 0xbd },
            lookAtPoint: { x: -21, y: 0x3a, z: 0xb6 },
            easeTime: 1.5,
            holdTime: 0x4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 0x5,
        intermission: 0xa,
        waves: [
          {
            waveName: "level.1.wave.1",
            zombieCount: 0x7,
            minSpawnInterval: 0x7,
            maxSpawnInterval: 0xa,
            mobs: ["bn:zombie"],
          },
          {
            waveName: "level.1.wave.2",
            zombieCount: 0x7,
            minSpawnInterval: 0x3,
            maxSpawnInterval: 0x5,
            mobs: ["bn:zombie"],
          },
        ],
        locations: [{ x: -22.5, y: 0x39, z: 192.5 }],
      },
      pollenSpawning: {
        spawnInterval: 0x7,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
  [
    "level2",
    {
      name: "level.2.name",
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "2_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [
        { x: -22.5, y: 0x39, z: 174.5 },
        { x: -19.5, y: 0x39, z: 174.5 },
      ],
      startItems: [
        { slot: 0x0, typeId: "bn:plant_1", amount: 0x1 },
        { slot: 0x1, typeId: "bn:plant_2", amount: 0x1 },
        { slot: 0x8, typeId: "bn:shovel", amount: 0x1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x32,
      zombieKillPoints: 0xa,
      unlocksPlant: {
        entityId: "bn:cherry_tnt",
        name: "level.2.unlock",
        spawnLocation: { x: -21, y: 0x3a, z: 0xb6 },
        scale: 0x3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 0x3c, z: 0xbd },
            lookAtPoint: { x: -21, y: 0x3a, z: 0xb6 },
            easeTime: 1.5,
            holdTime: 0x4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 0x23,
        intermission: 0xa,
        waves: [
          {
            waveName: "level.2.wave.1",
            zombieCount: 0xa,
            minSpawnInterval: 0x7,
            maxSpawnInterval: 0xa,
            mobs: ["bn:zombie"],
          },
          {
            waveName: "level.2.wave.2",
            zombieCount: 0x14,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x4,
            mobs: ["bn:zombie"],
          },
        ],
        locations: [
          { x: -22.5, y: 0x39, z: 192.5 },
          { x: -19.5, y: 0x39, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 0x7,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
  [
    "level3",
    {
      name: "level.3.name",
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "4_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [
        { x: -25.5, y: 0x39, z: 174.5 },
        { x: -22.5, y: 0x39, z: 174.5 },
        { x: -19.5, y: 0x39, z: 174.5 },
        { x: -16.5, y: 0x39, z: 174.5 },
      ],
      startItems: [
        { slot: 0x0, typeId: "bn:plant_1", amount: 0x1 },
        { slot: 0x1, typeId: "bn:plant_2", amount: 0x1 },
        { slot: 0x2, typeId: "bn:plant_3", amount: 0x1 },
        { slot: 0x8, typeId: "bn:shovel", amount: 0x1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x32,
      zombieKillPoints: 0xa,
      unlocksPlant: {
        entityId: "bn:wallnut",
        name: "level.3.unlock",
        spawnLocation: { x: -21, y: 0x3a, z: 0xb6 },
        scale: 0x3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 0x3c, z: 0xbd },
            lookAtPoint: { x: -21, y: 0x3a, z: 0xb6 },
            easeTime: 1.5,
            holdTime: 0x4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 0x28,
        intermission: 0xa,
        waves: [
          {
            waveName: "level.3.wave.1",
            zombieCount: 0xa,
            minSpawnInterval: 0x7,
            maxSpawnInterval: 0xc,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 0x1 }],
          },
          {
            waveName: "level.3.wave.2",
            zombieCount: 0x19,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x4,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 0x3 }],
          },
        ],
        locations: [
          { x: -25.5, y: 0x39, z: 192.5 },
          { x: -22.5, y: 0x39, z: 192.5 },
          { x: -19.5, y: 0x39, z: 192.5 },
          { x: -16.5, y: 0x39, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 0x7,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
  [
    "level4",
    {
      name: "level.4.name",
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 0x39, z: 174.5 },
        { x: -25.5, y: 0x39, z: 174.5 },
        { x: -22.5, y: 0x39, z: 174.5 },
        { x: -19.5, y: 0x39, z: 174.5 },
        { x: -16.5, y: 0x39, z: 174.5 },
        { x: -13.5, y: 0x39, z: 174.5 },
      ],
      startItems: [
        { slot: 0x0, typeId: "bn:plant_1", amount: 0x1 },
        { slot: 0x1, typeId: "bn:plant_2", amount: 0x1 },
        { slot: 0x2, typeId: "bn:plant_3", amount: 0x1 },
        { slot: 0x3, typeId: "bn:plant_4", amount: 0x1 },
        { slot: 0x8, typeId: "bn:shovel", amount: 0x1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x32,
      zombieKillPoints: 0xa,
      unlocksPlant: {
        entityId: "bn:potato_mine",
        name: "level.4.unlock",
        spawnLocation: { x: -21, y: 0x3a, z: 0xb6 },
        scale: 0x3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 0x3c, z: 0xbd },
            lookAtPoint: { x: -21, y: 0x3a, z: 0xb6 },
            easeTime: 1.5,
            holdTime: 0x4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 0x28,
        intermission: 0xa,
        waves: [
          {
            waveName: "level.4.wave.1",
            zombieCount: 0xf,
            minSpawnInterval: 0x7,
            maxSpawnInterval: 0xc,
            mobs: ["bn:zombie"],
          },
          {
            waveName: "level.4.wave.2",
            zombieCount: 0x19,
            minSpawnInterval: 0x4,
            maxSpawnInterval: 0x7,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 0x3 }],
          },
          {
            waveName: "level.4.wave.3",
            zombieCount: 0x1e,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x4,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 0x6 }],
          },
        ],
        locations: [
          { x: -28.5, y: 0x39, z: 192.5 },
          { x: -25.5, y: 0x39, z: 192.5 },
          { x: -22.5, y: 0x39, z: 192.5 },
          { x: -19.5, y: 0x39, z: 192.5 },
          { x: -16.5, y: 0x39, z: 192.5 },
          { x: -13.5, y: 0x39, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 0x6,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
  [
    "level5",
    {
      name: "level.5.name",
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 0x39, z: 174.5 },
        { x: -25.5, y: 0x39, z: 174.5 },
        { x: -22.5, y: 0x39, z: 174.5 },
        { x: -19.5, y: 0x39, z: 174.5 },
        { x: -16.5, y: 0x39, z: 174.5 },
        { x: -13.5, y: 0x39, z: 174.5 },
      ],
      startItems: [
        { slot: 0x0, typeId: "bn:plant_1", amount: 0x1 },
        { slot: 0x1, typeId: "bn:plant_2", amount: 0x1 },
        { slot: 0x2, typeId: "bn:plant_3", amount: 0x1 },
        { slot: 0x3, typeId: "bn:plant_4", amount: 0x1 },
        { slot: 0x4, typeId: "bn:plant_5", amount: 0x1 },
        { slot: 0x8, typeId: "bn:shovel", amount: 0x1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x32,
      zombieKillPoints: 0xa,
      unlocksPlant: {
        entityId: "bn:snow_pea",
        name: "level.5.unlock",
        spawnLocation: { x: -21, y: 0x3a, z: 0xb6 },
        scale: 0x3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 0x3c, z: 0xbd },
            lookAtPoint: { x: -21, y: 0x3a, z: 0xb6 },
            easeTime: 1.5,
            holdTime: 0x4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 0x2d,
        intermission: 0xa,
        waves: [
          {
            waveName: "level.5.wave.1",
            zombieCount: 0x14,
            minSpawnInterval: 0x7,
            maxSpawnInterval: 0xc,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 0x2 }],
          },
          {
            waveName: "level.5.wave.2",
            zombieCount: 0x1e,
            minSpawnInterval: 0x4,
            maxSpawnInterval: 0x7,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 0x5 }],
          },
          {
            waveName: "level.5.wave.3",
            zombieCount: 0x23,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x4,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 0xa }],
          },
        ],
        locations: [
          { x: -28.5, y: 0x39, z: 192.5 },
          { x: -25.5, y: 0x39, z: 192.5 },
          { x: -22.5, y: 0x39, z: 192.5 },
          { x: -19.5, y: 0x39, z: 192.5 },
          { x: -16.5, y: 0x39, z: 192.5 },
          { x: -13.5, y: 0x39, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 0x5,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
  [
    "level6",
    {
      name: "level.6.name",
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 0x39, z: 174.5 },
        { x: -25.5, y: 0x39, z: 174.5 },
        { x: -22.5, y: 0x39, z: 174.5 },
        { x: -19.5, y: 0x39, z: 174.5 },
        { x: -16.5, y: 0x39, z: 174.5 },
        { x: -13.5, y: 0x39, z: 174.5 },
      ],
      startItems: [
        { slot: 0x0, typeId: "bn:plant_1", amount: 0x1 },
        { slot: 0x1, typeId: "bn:plant_2", amount: 0x1 },
        { slot: 0x2, typeId: "bn:plant_3", amount: 0x1 },
        { slot: 0x3, typeId: "bn:plant_4", amount: 0x1 },
        { slot: 0x4, typeId: "bn:plant_5", amount: 0x1 },
        { slot: 0x5, typeId: "bn:plant_6", amount: 0x1 },
        { slot: 0x8, typeId: "bn:shovel", amount: 0x1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x32,
      zombieKillPoints: 0xa,
      zombieSpawning: {
        initialDelay: 0x2d,
        intermission: 0xa,
        waves: [
          {
            waveName: "level.6.wave.1",
            zombieCount: 0x19,
            minSpawnInterval: 0x7,
            maxSpawnInterval: 0xc,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0x4 },
              { typeId: "bn:zombie_bucket", count: 0x1 },
            ],
          },
          {
            waveName: "level.6.wave.2",
            zombieCount: 0x23,
            minSpawnInterval: 0x4,
            maxSpawnInterval: 0x7,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0x7 },
              { typeId: "bn:zombie_bucket", count: 0x3 },
            ],
          },
          {
            waveName: "level.6.wave.3",
            zombieCount: 0x28,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x4,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0xa },
              { typeId: "bn:zombie_bucket", count: 0x6 },
            ],
          },
        ],
        locations: [
          { x: -28.5, y: 0x39, z: 192.5 },
          { x: -25.5, y: 0x39, z: 192.5 },
          { x: -22.5, y: 0x39, z: 192.5 },
          { x: -19.5, y: 0x39, z: 192.5 },
          { x: -16.5, y: 0x39, z: 192.5 },
          { x: -13.5, y: 0x39, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 0x5,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
  [
    "level7",
    {
      name: "level.7.name",
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 0x39, z: 174.5 },
        { x: -25.5, y: 0x39, z: 174.5 },
        { x: -22.5, y: 0x39, z: 174.5 },
        { x: -19.5, y: 0x39, z: 174.5 },
        { x: -16.5, y: 0x39, z: 174.5 },
        { x: -13.5, y: 0x39, z: 174.5 },
      ],
      startItems: [
        { slot: 0x0, typeId: "bn:plant_1", amount: 0x1 },
        { slot: 0x1, typeId: "bn:plant_2", amount: 0x1 },
        { slot: 0x2, typeId: "bn:plant_3", amount: 0x1 },
        { slot: 0x3, typeId: "bn:plant_4", amount: 0x1 },
        { slot: 0x4, typeId: "bn:plant_5", amount: 0x1 },
        { slot: 0x5, typeId: "bn:plant_6", amount: 0x1 },
        { slot: 0x8, typeId: "bn:shovel", amount: 0x1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x32,
      zombieKillPoints: 0xa,
      zombieSpawning: {
        initialDelay: 0x2d,
        intermission: 0x8,
        waves: [
          {
            waveName: "level.7.wave.1",
            zombieCount: 0x1e,
            minSpawnInterval: 0x8,
            maxSpawnInterval: 0xc,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0x8 },
              { typeId: "bn:zombie_bucket", count: 0x3 },
            ],
          },
          {
            waveName: "level.7.wave.2",
            zombieCount: 0x28,
            minSpawnInterval: 0x3,
            maxSpawnInterval: 0x6,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0xc },
              { typeId: "bn:zombie_bucket", count: 0x6 },
            ],
          },
          {
            waveName: "level.7.wave.3",
            zombieCount: 0x32,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x4,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0xf },
              { typeId: "bn:zombie_bucket", count: 0xa },
            ],
          },
        ],
        locations: [
          { x: -28.5, y: 0x39, z: 192.5 },
          { x: -25.5, y: 0x39, z: 192.5 },
          { x: -22.5, y: 0x39, z: 192.5 },
          { x: -19.5, y: 0x39, z: 192.5 },
          { x: -16.5, y: 0x39, z: 192.5 },
          { x: -13.5, y: 0x39, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 0x4,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
  [
    "level8",
    {
      name: "level.8.name",
      playerStartLocation: { x: -20.93, y: 0x41, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 0x37, z: 0xaf } },
      cutscene: [
        {
          location: { x: -31, y: 0x3c, z: 0xb2 },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
        {
          location: { x: -30, y: 0x3c, z: 0xcc },
          lookAtPoint: { x: -22, y: 0x3b, z: 0xae },
          easeTime: 1.5,
          holdTime: 0x1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 0x39, z: 174.5 },
        { x: -25.5, y: 0x39, z: 174.5 },
        { x: -22.5, y: 0x39, z: 174.5 },
        { x: -19.5, y: 0x39, z: 174.5 },
        { x: -16.5, y: 0x39, z: 174.5 },
        { x: -13.5, y: 0x39, z: 174.5 },
      ],
      startItems: [
        { slot: 0x0, typeId: "bn:plant_1", amount: 0x1 },
        { slot: 0x1, typeId: "bn:plant_2", amount: 0x1 },
        { slot: 0x2, typeId: "bn:plant_3", amount: 0x1 },
        { slot: 0x3, typeId: "bn:plant_4", amount: 0x1 },
        { slot: 0x4, typeId: "bn:plant_5", amount: 0x1 },
        { slot: 0x5, typeId: "bn:plant_6", amount: 0x1 },
        { slot: 0x8, typeId: "bn:shovel", amount: 0x1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0x32,
      zombieKillPoints: 0xa,
      zombieSpawning: {
        initialDelay: 0x2d,
        intermission: 0x5,
        waves: [
          {
            waveName: "level.8.wave.1",
            zombieCount: 0x28,
            minSpawnInterval: 0x7,
            maxSpawnInterval: 0xb,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0xa },
              { typeId: "bn:zombie_bucket", count: 0x5 },
            ],
          },
          {
            waveName: "level.8.wave.2",
            zombieCount: 0x32,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x5,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0xf },
              { typeId: "bn:zombie_bucket", count: 0xa },
            ],
          },
          {
            waveName: "level.8.wave.3",
            zombieCount: 0x46,
            minSpawnInterval: 0x2,
            maxSpawnInterval: 0x3,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 0x19 },
              { typeId: "bn:zombie_bucket", count: 0xf },
            ],
          },
        ],
        locations: [
          { x: -28.5, y: 0x39, z: 192.5 },
          { x: -25.5, y: 0x39, z: 192.5 },
          { x: -22.5, y: 0x39, z: 192.5 },
          { x: -19.5, y: 0x39, z: 192.5 },
          { x: -16.5, y: 0x39, z: 192.5 },
          { x: -13.5, y: 0x39, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 0x3,
        centerLocation: { x: -21, y: 0x45, z: 0xb6 },
        radius: 0xa,
      },
    },
  ],
]);
