export const levelData = new Map([
  [
    "level1",
    {
      name: "level.1.name",
      isTutorial: true,
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "1_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [{ x: -22.5, y: 57, z: 174.5 }],
      startItems: [],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 0,
      zombieKillPoints: 10,
      unlocksPlant: {
        entityId: "bn:sunflower",
        name: "level.1.unlock",
        spawnLocation: { x: -21, y: 58, z: 182 },
        scale: 3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 60, z: 189 },
            lookAtPoint: { x: -21, y: 58, z: 182 },
            easeTime: 1.5,
            holdTime: 4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 5,
        intermission: 10,
        waves: [
          {
            waveName: "level.1.wave.1",
            zombieCount: 7,
            minSpawnInterval: 7,
            maxSpawnInterval: 10,
            mobs: ["bn:zombie"],
          },
          {
            waveName: "level.1.wave.2",
            zombieCount: 7,
            minSpawnInterval: 3,
            maxSpawnInterval: 5,
            mobs: ["bn:zombie"],
          },
        ],
        locations: [{ x: -22.5, y: 57, z: 192.5 }],
      },
      pollenSpawning: {
        spawnInterval: 7,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
  [
    "level2",
    {
      name: "level.2.name",
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "2_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [
        { x: -22.5, y: 57, z: 174.5 },
        { x: -19.5, y: 57, z: 174.5 },
      ],
      startItems: [
        { slot: 0, typeId: "bn:plant_1", amount: 1 },
        { slot: 1, typeId: "bn:plant_2", amount: 1 },
        { slot: 8, typeId: "bn:shovel", amount: 1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 50,
      zombieKillPoints: 10,
      unlocksPlant: {
        entityId: "bn:cherry_tnt",
        name: "level.2.unlock",
        spawnLocation: { x: -21, y: 58, z: 182 },
        scale: 3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 60, z: 189 },
            lookAtPoint: { x: -21, y: 58, z: 182 },
            easeTime: 1.5,
            holdTime: 4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 35,
        intermission: 10,
        waves: [
          {
            waveName: "level.2.wave.1",
            zombieCount: 10,
            minSpawnInterval: 7,
            maxSpawnInterval: 10,
            mobs: ["bn:zombie"],
          },
          {
            waveName: "level.2.wave.2",
            zombieCount: 20,
            minSpawnInterval: 2,
            maxSpawnInterval: 4,
            mobs: ["bn:zombie"],
          },
        ],
        locations: [
          { x: -22.5, y: 57, z: 192.5 },
          { x: -19.5, y: 57, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 7,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
  [
    "level3",
    {
      name: "level.3.name",
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "4_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [
        { x: -25.5, y: 57, z: 174.5 },
        { x: -22.5, y: 57, z: 174.5 },
        { x: -19.5, y: 57, z: 174.5 },
        { x: -16.5, y: 57, z: 174.5 },
      ],
      startItems: [
        { slot: 0, typeId: "bn:plant_1", amount: 1 },
        { slot: 1, typeId: "bn:plant_2", amount: 1 },
        { slot: 2, typeId: "bn:plant_3", amount: 1 },
        { slot: 8, typeId: "bn:shovel", amount: 1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 50,
      zombieKillPoints: 10,
      unlocksPlant: {
        entityId: "bn:wallnut",
        name: "level.3.unlock",
        spawnLocation: { x: -21, y: 58, z: 182 },
        scale: 3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 60, z: 189 },
            lookAtPoint: { x: -21, y: 58, z: 182 },
            easeTime: 1.5,
            holdTime: 4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 40,
        intermission: 10,
        waves: [
          {
            waveName: "level.3.wave.1",
            zombieCount: 10,
            minSpawnInterval: 7,
            maxSpawnInterval: 12,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 1 }],
          },
          {
            waveName: "level.3.wave.2",
            zombieCount: 25,
            minSpawnInterval: 2,
            maxSpawnInterval: 4,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 3 }],
          },
        ],
        locations: [
          { x: -25.5, y: 57, z: 192.5 },
          { x: -22.5, y: 57, z: 192.5 },
          { x: -19.5, y: 57, z: 192.5 },
          { x: -16.5, y: 57, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 7,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
  [
    "level4",
    {
      name: "level.4.name",
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 57, z: 174.5 },
        { x: -25.5, y: 57, z: 174.5 },
        { x: -22.5, y: 57, z: 174.5 },
        { x: -19.5, y: 57, z: 174.5 },
        { x: -16.5, y: 57, z: 174.5 },
        { x: -13.5, y: 57, z: 174.5 },
      ],
      startItems: [
        { slot: 0, typeId: "bn:plant_1", amount: 1 },
        { slot: 1, typeId: "bn:plant_2", amount: 1 },
        { slot: 2, typeId: "bn:plant_3", amount: 1 },
        { slot: 3, typeId: "bn:plant_4", amount: 1 },
        { slot: 8, typeId: "bn:shovel", amount: 1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 50,
      zombieKillPoints: 10,
      unlocksPlant: {
        entityId: "bn:potato_mine",
        name: "level.4.unlock",
        spawnLocation: { x: -21, y: 58, z: 182 },
        scale: 3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 60, z: 189 },
            lookAtPoint: { x: -21, y: 58, z: 182 },
            easeTime: 1.5,
            holdTime: 4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 40,
        intermission: 10,
        waves: [
          {
            waveName: "level.4.wave.1",
            zombieCount: 15,
            minSpawnInterval: 7,
            maxSpawnInterval: 12,
            mobs: ["bn:zombie"],
          },
          {
            waveName: "level.4.wave.2",
            zombieCount: 25,
            minSpawnInterval: 4,
            maxSpawnInterval: 7,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 3 }],
          },
          {
            waveName: "level.4.wave.3",
            zombieCount: 30,
            minSpawnInterval: 2,
            maxSpawnInterval: 4,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 6 }],
          },
        ],
        locations: [
          { x: -28.5, y: 57, z: 192.5 },
          { x: -25.5, y: 57, z: 192.5 },
          { x: -22.5, y: 57, z: 192.5 },
          { x: -19.5, y: 57, z: 192.5 },
          { x: -16.5, y: 57, z: 192.5 },
          { x: -13.5, y: 57, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 6,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
  [
    "level5",
    {
      name: "level.5.name",
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 57, z: 174.5 },
        { x: -25.5, y: 57, z: 174.5 },
        { x: -22.5, y: 57, z: 174.5 },
        { x: -19.5, y: 57, z: 174.5 },
        { x: -16.5, y: 57, z: 174.5 },
        { x: -13.5, y: 57, z: 174.5 },
      ],
      startItems: [
        { slot: 0, typeId: "bn:plant_1", amount: 1 },
        { slot: 1, typeId: "bn:plant_2", amount: 1 },
        { slot: 2, typeId: "bn:plant_3", amount: 1 },
        { slot: 3, typeId: "bn:plant_4", amount: 1 },
        { slot: 4, typeId: "bn:plant_5", amount: 1 },
        { slot: 8, typeId: "bn:shovel", amount: 1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 50,
      zombieKillPoints: 10,
      unlocksPlant: {
        entityId: "bn:snow_pea",
        name: "level.5.unlock",
        spawnLocation: { x: -21, y: 58, z: 182 },
        scale: 3,
        onSpawnEvents: ["bn:unlock"],
        cutscene: [
          {
            location: { x: -22, y: 60, z: 189 },
            lookAtPoint: { x: -21, y: 58, z: 182 },
            easeTime: 1.5,
            holdTime: 4,
          },
        ],
      },
      zombieSpawning: {
        initialDelay: 45,
        intermission: 10,
        waves: [
          {
            waveName: "level.5.wave.1",
            zombieCount: 20,
            minSpawnInterval: 7,
            maxSpawnInterval: 12,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 2 }],
          },
          {
            waveName: "level.5.wave.2",
            zombieCount: 30,
            minSpawnInterval: 4,
            maxSpawnInterval: 7,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 5 }],
          },
          {
            waveName: "level.5.wave.3",
            zombieCount: 35,
            minSpawnInterval: 2,
            maxSpawnInterval: 4,
            mobs: ["bn:zombie"],
            specialZombies: [{ typeId: "bn:zombie_cone", count: 10 }],
          },
        ],
        locations: [
          { x: -28.5, y: 57, z: 192.5 },
          { x: -25.5, y: 57, z: 192.5 },
          { x: -22.5, y: 57, z: 192.5 },
          { x: -19.5, y: 57, z: 192.5 },
          { x: -16.5, y: 57, z: 192.5 },
          { x: -13.5, y: 57, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 5,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
  [
    "level6",
    {
      name: "level.6.name",
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 57, z: 174.5 },
        { x: -25.5, y: 57, z: 174.5 },
        { x: -22.5, y: 57, z: 174.5 },
        { x: -19.5, y: 57, z: 174.5 },
        { x: -16.5, y: 57, z: 174.5 },
        { x: -13.5, y: 57, z: 174.5 },
      ],
      startItems: [
        { slot: 0, typeId: "bn:plant_1", amount: 1 },
        { slot: 1, typeId: "bn:plant_2", amount: 1 },
        { slot: 2, typeId: "bn:plant_3", amount: 1 },
        { slot: 3, typeId: "bn:plant_4", amount: 1 },
        { slot: 4, typeId: "bn:plant_5", amount: 1 },
        { slot: 5, typeId: "bn:plant_6", amount: 1 },
        { slot: 8, typeId: "bn:shovel", amount: 1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 50,
      zombieKillPoints: 10,
      zombieSpawning: {
        initialDelay: 45,
        intermission: 10,
        waves: [
          {
            waveName: "level.6.wave.1",
            zombieCount: 25,
            minSpawnInterval: 7,
            maxSpawnInterval: 12,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 4 },
              { typeId: "bn:zombie_bucket", count: 1 },
            ],
          },
          {
            waveName: "level.6.wave.2",
            zombieCount: 35,
            minSpawnInterval: 4,
            maxSpawnInterval: 7,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 7 },
              { typeId: "bn:zombie_bucket", count: 3 },
            ],
          },
          {
            waveName: "level.6.wave.3",
            zombieCount: 40,
            minSpawnInterval: 2,
            maxSpawnInterval: 4,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 10 },
              { typeId: "bn:zombie_bucket", count: 6 },
            ],
          },
        ],
        locations: [
          { x: -28.5, y: 57, z: 192.5 },
          { x: -25.5, y: 57, z: 192.5 },
          { x: -22.5, y: 57, z: 192.5 },
          { x: -19.5, y: 57, z: 192.5 },
          { x: -16.5, y: 57, z: 192.5 },
          { x: -13.5, y: 57, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 5,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
  [
    "level7",
    {
      name: "level.7.name",
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 57, z: 174.5 },
        { x: -25.5, y: 57, z: 174.5 },
        { x: -22.5, y: 57, z: 174.5 },
        { x: -19.5, y: 57, z: 174.5 },
        { x: -16.5, y: 57, z: 174.5 },
        { x: -13.5, y: 57, z: 174.5 },
      ],
      startItems: [
        { slot: 0, typeId: "bn:plant_1", amount: 1 },
        { slot: 1, typeId: "bn:plant_2", amount: 1 },
        { slot: 2, typeId: "bn:plant_3", amount: 1 },
        { slot: 3, typeId: "bn:plant_4", amount: 1 },
        { slot: 4, typeId: "bn:plant_5", amount: 1 },
        { slot: 5, typeId: "bn:plant_6", amount: 1 },
        { slot: 8, typeId: "bn:shovel", amount: 1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 50,
      zombieKillPoints: 10,
      zombieSpawning: {
        initialDelay: 45,
        intermission: 8,
        waves: [
          {
            waveName: "level.7.wave.1",
            zombieCount: 30,
            minSpawnInterval: 8,
            maxSpawnInterval: 12,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 8 },
              { typeId: "bn:zombie_bucket", count: 3 },
            ],
          },
          {
            waveName: "level.7.wave.2",
            zombieCount: 40,
            minSpawnInterval: 3,
            maxSpawnInterval: 6,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 12 },
              { typeId: "bn:zombie_bucket", count: 6 },
            ],
          },
          {
            waveName: "level.7.wave.3",
            zombieCount: 50,
            minSpawnInterval: 2,
            maxSpawnInterval: 4,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 15 },
              { typeId: "bn:zombie_bucket", count: 10 },
            ],
          },
        ],
        locations: [
          { x: -28.5, y: 57, z: 192.5 },
          { x: -25.5, y: 57, z: 192.5 },
          { x: -22.5, y: 57, z: 192.5 },
          { x: -19.5, y: 57, z: 192.5 },
          { x: -16.5, y: 57, z: 192.5 },
          { x: -13.5, y: 57, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 4,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
  [
    "level8",
    {
      name: "level.8.name",
      playerStartLocation: { x: -20.93, y: 65, z: 172.83 },
      structure: { name: "6_rows", location: { x: -30, y: 55, z: 175 } },
      cutscene: [
        {
          location: { x: -31, y: 60, z: 178 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
        {
          location: { x: -30, y: 60, z: 204 },
          lookAtPoint: { x: -22, y: 59, z: 174 },
          easeTime: 1.5,
          holdTime: 1,
        },
      ],
      lawnmowers: [
        { x: -28.5, y: 57, z: 174.5 },
        { x: -25.5, y: 57, z: 174.5 },
        { x: -22.5, y: 57, z: 174.5 },
        { x: -19.5, y: 57, z: 174.5 },
        { x: -16.5, y: 57, z: 174.5 },
        { x: -13.5, y: 57, z: 174.5 },
      ],
      startItems: [
        { slot: 0, typeId: "bn:plant_1", amount: 1 },
        { slot: 1, typeId: "bn:plant_2", amount: 1 },
        { slot: 2, typeId: "bn:plant_3", amount: 1 },
        { slot: 3, typeId: "bn:plant_4", amount: 1 },
        { slot: 4, typeId: "bn:plant_5", amount: 1 },
        { slot: 5, typeId: "bn:plant_6", amount: 1 },
        { slot: 8, typeId: "bn:shovel", amount: 1 },
      ],
      scoreboardsToReset: ["pollen", "points"],
      startingPollen: 50,
      zombieKillPoints: 10,
      zombieSpawning: {
        initialDelay: 45,
        intermission: 5,
        waves: [
          {
            waveName: "level.8.wave.1",
            zombieCount: 40,
            minSpawnInterval: 7,
            maxSpawnInterval: 11,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 10 },
              { typeId: "bn:zombie_bucket", count: 5 },
            ],
          },
          {
            waveName: "level.8.wave.2",
            zombieCount: 50,
            minSpawnInterval: 2,
            maxSpawnInterval: 5,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 15 },
              { typeId: "bn:zombie_bucket", count: 10 },
            ],
          },
          {
            waveName: "level.8.wave.3",
            zombieCount: 70,
            minSpawnInterval: 2,
            maxSpawnInterval: 3,
            mobs: ["bn:zombie"],
            specialZombies: [
              { typeId: "bn:zombie_cone", count: 25 },
              { typeId: "bn:zombie_bucket", count: 15 },
            ],
          },
        ],
        locations: [
          { x: -28.5, y: 57, z: 192.5 },
          { x: -25.5, y: 57, z: 192.5 },
          { x: -22.5, y: 57, z: 192.5 },
          { x: -19.5, y: 57, z: 192.5 },
          { x: -16.5, y: 57, z: 192.5 },
          { x: -13.5, y: 57, z: 192.5 },
        ],
      },
      pollenSpawning: {
        spawnInterval: 3,
        centerLocation: { x: -21, y: 69, z: 182 },
        radius: 10,
      },
    },
  ],
]);
