/**
* PvZ Style Game - LanguageManager.js
* * This script handles all language and translation logic.
*/

import { world } from "@minecraft/server";

const LANGUAGE_KEY = "playerLanguage";

// Define all translatable strings here
const translations = {
    // English (en)
    en: {
        "language.name": "English",
        "menu.title": "Game Menu",
        "menu.body": "Select a category to get started!",
        "menu.category.levels": "Levels",
        "menu.category.shop": "Shop",
        "menu.category.settings": "Settings",
        "menu.level": "Level {0}",
        "menu.shop.button": "     Shop\n(Coming Soon)",
        "menu.settings.plant_health": "   Plant\nHealth: {0}",
        "menu.settings.zombie_health": "   Zombie\nHealth: {0}",
        "menu.settings.dialogue": " Dialogue: {0}",
        "menu.settings.language": " Language:\n {0}",
        "menu.settings.reset_progress": "§cReset All\nProgress",
        "menu.shop.not_implemented": "§eThe Shop is not yet implemented.",
        "menu.level.locked": "§cThis level is locked! Complete the previous level to unlock it.",
        "menu.level.in_progress": "§cA level is already in progress! You cannot start a new one.",
        "misc.on": "§aOn",
        "misc.off": "§cOff",
        "misc.interact_prompt": "§eSpeak to Crazy Dave to get started!",
        "game.title": "§2P§al§2a§an§2t§as §6VS §7Z§8o§7m§8b§7i§8e§7s",
        "game.sun_counter": "§eSun: {0}",
        "game.plant_cooldown": "§7{0}: {1}s",
        "game.wave_cleared": "§6Wave Cleared!",
        "game.next_wave_in": "Next wave in {0} seconds.",
        "game.level_start": "§aStarting {0}!",
        "game.wave_approaching": "A new wave of zombies is approaching!",
        "game.plant_unlocked": "§aYou've unlocked a new plant!",
        "game.collect_plant_prompt": "§eCollect the {0} to continue.",
        "game.level_complete": "§a§lLEVEL COMPLETE!",
        "game.game_over": "§c§lGAME OVER",
        "game.win_message": "§aYou survived all the waves!",
        "game.lose_message": "§cThe zombies reached your house!",
        "plant.on_cooldown": "§c{0} is on cooldown for {1}s.",
        "plant.not_enough_pollen": "§cNot enough sun! {0} costs {1}.",
        "plant.invalid_surface": "§cYou must plant on a surface with a gold or iron block foundation!",
        "plant.no_foundation": "§cCould not find a complete 3x2 foundation of the same block type!",
        "plant.space_occupied": "§cYou can't plant here, the space is occupied by another plant!",
        "reset.confirm.title": "§cConfirm Reset",
        "reset.confirm.body": "§4Are you sure you want to reset all level progress? This action cannot be undone.",
        "reset.confirm.yes": "§cYes, Reset Progress",
        "reset.confirm.no": "§aNo, Cancel",
        "reset.success": "§eAll level progress has been reset.",
        "reset.cancelled": "§aProgress reset cancelled.",
        "shop.title": "Plant Shop",
        "shop.body": "Your Sun: §e{0}",
        "shop.item_button": "{0}\n§eCost: {1}",
        "shop.purchase_success": "§aYou purchased a {0}!",
        "shop.not_enough_pollen": "§cYou don't have enough sun to buy that!",
        "tutorial.welcome.title": "§eWelcome to the Tutorial!",
        "tutorial.welcome.subtitle": "Let's learn the basics.",
        "tutorial.task.collect_first_pollen": "§aTask: Collect your first sun!\n§7Look at the sun and swing your arm to collect it,\nor Walk up to it.",
        "tutorial.task.collect_for_peashooter": "§aTask: Collect enough sun to purchase a Peashooter!\n§7Each sun is worth 25 points §e({0} / {1}§a)",
        "tutorial.task.place_first_peashooter": "§aTask: Plant your first Peashooter!\n§7Hold the Peashooter item in your hand,\nlook at a valid tile, and use the item to plant it.",
        "tutorial.task.collect_for_second": "§aTask: Great! Collect enough for a second plant. (§e{0} / {1}§a)",
        "tutorial.task.place_second_peashooter": "§aTask: Plant your second Peashooter to begin!",
        "tutorial.complete.title": "§aTutorial Complete!",
        "tutorial.complete.subtitle": "Get ready for the zombies!",
        "entity.crazy_steve.name": "Crazy Dave",
        "dialogue.crazy_steve.1": "Wabby-wabbo!",
        "dialogue.crazy_steve.2": "Have you seen my lucky\npan? I wear it on\nmy head!",
        "dialogue.crazy_steve.3": "The zombies are coming! Quick,\ngrab the... uh... thingamajig!",
        "dialogue.crazy_steve.4": "Did you know tacos are\nthe best brain food? That's\nwhy I'm so smart!",
        "dialogue.crazy_steve.5": "I'm not crazy, my reality\nis just different than yours.",
        "dialogue.crazy_steve.6": "If a zombie eats a\nclown, does it taste funny?",
        "dialogue.crazy_steve.7": "My favorite plant is the...\nshiny one!",
        "dialogue.crazy_steve.8": "I once tried to reason\nwith a zombie. He was\na bit of a blockhead.",
        "dialogue.crazy_steve.9": "Time to get this party\nstarted! With... plants!",
        "dialogue.crazy_steve.10": "Because I'm CRAAAAAZY!",
        "dialogue.crazy_steve.11": "I put the 'fun' in\n'fungus'!",
        "dialogue.crazy_steve.12": "I told my lawn to\n'get off my zombies!'... It\ndidn't listen.",
        "level.1.name": "Level 1: Tutorial",
        "level.1.wave.1": "Wave 1",
        "level.1.wave.2": "Final Wave",
        "level.1.unlock": "Sunflower",
        "level.2.name": "Level 2: The Bigger Lawn",
        "level.2.wave.1": "Wave 1",
        "level.2.wave.2": "Final Wave",
        "level.2.unlock": "Cherry Bomb",
        "level.3.name": "Level 3: Conehead Kerfuffle",
        "level.3.wave.1": "Wave 1",
        "level.3.wave.2": "Final Wave",
        "level.3.unlock": "Wall-nut",
        "level.4.name": "Level 4: Buckethead Brigade",
        "level.4.wave.1": "Wave 1",
        "level.4.wave.2": "Wave 2",
        "level.4.wave.3": "Final Wave",
        "level.4.unlock": "Potato Mine",
        "level.5.name": "Level 5: Potato Power",
        "level.5.wave.1": "Wave 1",
        "level.5.wave.2": "Wave 2",
        "level.5.wave.3": "Final Wave",
        "level.5.unlock": "Snow Pea",
        "level.6.name": "Level 6: The Bucketheads are Back",
        "level.6.wave.1": "Wave 1",
        "level.6.wave.2": "Wave 2",
        "level.6.wave.3": "Final Wave",
        "level.7.name": "Level 7: Zombie Tsunami",
        "level.7.wave.1": "Wave 1",
        "level.7.wave.2": "Wave 2",
        "level.7.wave.3": "Final Wave",
        "level.8.name": "Level 8: The Final Stand",
        "level.8.wave.1": "Wave 1",
        "level.8.wave.2": "Wave 2",
        "level.8.wave.3": "Final Wave",
        "plant.sunflower.name": "Sunflower",
        "plant.peashooter.name": "Peashooter",
        "plant.cherry_bomb.name": "Cherry Bomb",
        "plant.wallnut.name": "Wall-nut",
        "plant.potato_mine.name": "Potato Mine",
        "plant.snow_pea.name": "Snow Pea",
        "plant.big_walnut.name": "Big Walnut",
    },
    // Spanish (es)
    es: {
        "language.name": "Español",
        "menu.title": "Menú del Juego",
        "menu.body": "¡Selecciona una categoría para comenzar!",
        "menu.category.levels": "Niveles",
        "menu.category.shop": "Tienda",
        "menu.category.settings": "Ajustes",
        "menu.level": "Nivel {0}",
        "menu.shop.button": "    Tienda\n(Próximamente)",
        "menu.settings.plant_health": "  Vida de la\n  Planta: {0}",
        "menu.settings.zombie_health": " Vida del\n Zombi: {0}",
        "menu.settings.dialogue": " Diálogo: {0}",
        "menu.settings.language": " Idioma:\n {0}",
        "menu.settings.reset_progress": "§cReiniciar Todo\nel Progreso",
        "menu.shop.not_implemented": "§eLa Tienda aún no está implementada.",
        "menu.level.locked": "¡Este nivel está bloqueado! Completa el nivel anterior para desbloquearlo.",
        "menu.level.in_progress": "¡Ya hay un nivel en progreso! No puedes empezar uno nuevo.",
        "misc.on": "§aSí",
        "misc.off": "§cNo",
        "misc.interact_prompt": "§e¡Habla con Crazy Dave para empezar!",
        "game.title": "§2P§al§2a§an§2t§as §6CONTRA §7Z§8o§7m§8b§7i§8s",
        "game.sun_counter": "§eSol: {0}",
        "game.plant_cooldown": "§7{0}: {1}s",
        "game.wave_cleared": "§6¡Oleada Superada!",
        "game.next_wave_in": "Siguiente oleada en {0} segundos.",
        "game.level_start": "§a¡Empezando {0}!",
        "game.wave_approaching": "¡Se acerca una nueva oleada de zombis!",
        "game.plant_unlocked": "§a¡Has desbloqueado una nueva planta!",
        "game.collect_plant_prompt": "§eRecoge la {0} para continuar.",
        "game.level_complete": "§a§l¡NIVEL COMPLETADO!",
        "game.game_over": "§c§l¡FIN DEL JUEGO!",
        "game.win_message": "§a¡Sobreviviste a todas las oleadas!",
        "game.lose_message": "§c¡Los zombis llegaron a tu casa!",
        "plant.on_cooldown": "§c{0} está en enfriamiento por {1}s.",
        "plant.not_enough_pollen": "§c¡No hay suficiente sol! {0} cuesta {1}.",
        "plant.invalid_surface": "§c¡Debes plantar en una superficie con una base de bloque de oro o hierro!",
        "plant.no_foundation": "§c¡No se pudo encontrar una base completa de 3x2 del mismo tipo de bloque!",
        "plant.space_occupied": "§c¡No puedes plantar aquí, el espacio está ocupado por otra planta!",
        "reset.confirm.title": "§cConfirmar Reinicio",
        "reset.confirm.body": "§4¿Estás seguro de que quieres reiniciar todo el progreso de los niveles? Esta acción no se puede deshacer.",
        "reset.confirm.yes": "§cSí, Reiniciar Progreso",
        "reset.confirm.no": "§aNo, Cancelar",
        "reset.success": "§eSe ha reiniciado todo el progreso de los niveles.",
        "reset.cancelled": "§aReinicio de progreso cancelado.",
        "shop.title": "Tienda de Plantas",
        "shop.body": "Tu Sol: §e{0}",
        "shop.item_button": "{0}\n§eCosto: {1}",
        "shop.purchase_success": "§a¡Compraste un {0}!",
        "shop.not_enough_pollen": "§c¡No tienes suficiente sol para comprar eso!",
        "tutorial.welcome.title": "§e¡Bienvenido al Tutorial!",
        "tutorial.welcome.subtitle": "Aprendamos lo básico.",
        "tutorial.task.collect_first_pollen": "§aTarea: ¡Recoge tu primer sol!\n§7Mira al sol y agita tu brazo para recogerlo,\no camina hacia él.",
        "tutorial.task.collect_for_peashooter": "§aTarea: ¡Recoge suficiente sol para comprar un Lanzaguisantes!\n§7Cada sol vale 25 puntos §e({0} / {1}§a)",
        "tutorial.task.place_first_peashooter": "§aTarea: ¡Planta tu primer Lanzaguisantes!\n§7Sostén el objeto Lanzaguisantes en tu mano,\nmira una casilla válida y usa el objeto para plantarlo.",
        "tutorial.task.collect_for_second": "§aTarea: ¡Genial! Recoge suficiente para una segunda planta. (§e{0} / {1}§a)",
        "tutorial.task.place_second_peashooter": "§aTarea: ¡Planta tu segundo Lanzaguisantes para comenzar!",
        "tutorial.complete.title": "§a¡Tutorial Completado!",
        "tutorial.complete.subtitle": "¡Prepárate para los zombis!",
        "entity.crazy_steve.name": "Crazy Dave",
        "dialogue.crazy_steve.1": "¡Wabby-wabbo!",
        "dialogue.crazy_steve.2": "¿Has visto mi sartén\nde la suerte? ¡La llevo\nen la cabeza!",
        "dialogue.crazy_steve.3": "¡Vienen los zombis! Rápido,\n¡coge el... el... cacharro!",
        "dialogue.crazy_steve.4": "¿Sabías que los tacos son\nel mejor alimento para el cerebro?\n¡Por eso soy tan listo!",
        "dialogue.crazy_steve.5": "No estoy loco, mi realidad\nes simplemente diferente a la tuya.",
        "dialogue.crazy_steve.6": "Si un zombi se come\nun payaso, ¿sabe a chiste?",
        "dialogue.crazy_steve.7": "Mi planta favorita es la...\n¡brillante!",
        "dialogue.crazy_steve.8": "Una vez intenté razonar\ncon un zombi. Era un\npoco cabeza hueca.",
        "dialogue.crazy_steve.9": "¡Es hora de que empiece\nla fiesta! ¡Con... plantas!",
        "dialogue.crazy_steve.10": "¡Porque estoy LOCOOOOO!",
        "dialogue.crazy_steve.11": "¡Le pongo lo 'divertido'\na los 'hongos'!",
        "dialogue.crazy_steve.12": "Le dije a mi césped que\n'se quitara de mis zombis!'...\nNo me hizo caso.",
        "level.1.name": "Nivel 1: Tutorial",
        "level.1.wave.1": "Oleada 1",
        "level.1.wave.2": "Oleada Final",
        "level.1.unlock": "Girasol",
        "level.2.name": "Nivel 2: El Jardín Más Grande",
        "level.2.wave.1": "Oleada 1",
        "level.2.wave.2": "Oleada Final",
        "level.2.unlock": "Bomba Cereza",
        "level.3.name": "Nivel 3: Confusión de Conos",
        "level.3.wave.1": "Oleada 1",
        "level.3.wave.2": "Oleada Final",
        "level.3.unlock": "Nuez",
        "level.4.name": "Nivel 4: Brigada de Cubos",
        "level.4.wave.1": "Oleada 1",
        "level.4.wave.2": "Oleada 2",
        "level.4.wave.3": "Oleada Final",
        "level.4.unlock": "Mina de Patata",
        "level.5.name": "Nivel 5: Poder de la Patata",
        "level.5.wave.1": "Oleada 1",
        "level.5.wave.2": "Oleada 2",
        "level.5.wave.3": "Oleada Final",
        "level.5.unlock": "Lanzaguisantes de Hielo",
        "level.6.name": "Nivel 6: Los Cabeza de Cubo Han Vuelto",
        "level.6.wave.1": "Oleada 1",
        "level.6.wave.2": "Oleada 2",
        "level.6.wave.3": "Oleada Final",
        "level.7.name": "Nivel 7: Tsunami de Zombis",
        "level.7.wave.1": "Oleada 1",
        "level.7.wave.2": "Oleada 2",
        "level.7.wave.3": "Oleada Final",
        "level.8.name": "Nivel 8: La Batalla Final",
        "level.8.wave.1": "Oleada 1",
        "level.8.wave.2": "Oleada 2",
        "level.8.wave.3": "Oleada Final",
        "plant.sunflower.name": "Girasol",
        "plant.peashooter.name": "Lanzaguisantes",
        "plant.cherry_bomb.name": "Bomba Cereza",
        "plant.wallnut.name": "Nuez",
        "plant.potato_mine.name": "Mina de Patata",
        "plant.snow_pea.name": "Lanzaguisantes de Hielo",
        "plant.big_walnut.name": "Nuez Grande",
    },
    // Arabic (ar)
    ar: {
        "language.name": "العربية",
        "menu.title": "قائمة اللعبة",
        "menu.body": "اختر فئة للبدء!",
        "menu.category.levels": "المستويات",
        "menu.category.shop": "المتجر",
        "menu.category.settings": "الإعدادات",
        "menu.level": "المستوى {0}",
        "menu.shop.button": "     المتجر\n(قريبًا)",
        "menu.settings.plant_health": "   صحة\nالنبات: {0}",
        "menu.settings.zombie_health": "   صحة\nالزومبي: {0}",
        "menu.settings.dialogue": " حوار: {0}",
        "menu.settings.language": " اللغة:\n {0}",
        "menu.settings.reset_progress": "§cإعادة تعيين كل\nالتقدم",
        "menu.shop.not_implemented": "§eالمتجر غير متاح بعد.",
        "menu.level.locked": "§cهذا المستوى مقفل! أكمل المستوى السابق لفتحه.",
        "menu.level.in_progress": "§cهناك مستوى قيد التقدم بالفعل! لا يمكنك بدء مستوى جديد.",
        "misc.on": "§aتشغيل",
        "misc.off": "§cإيقاف",
        "misc.interact_prompt": "§eتحدث إلى كريزي ديف للبدء!",
        "game.title": "§2ن§aب§2ا§aت§2ا§aت §6ضد §7ز§8و§7م§8ب§7ي",
        "game.sun_counter": "§eالشمس: {0}",
        "game.plant_cooldown": "§7{0}: {1}ث",
        "game.wave_cleared": "§6تم صد الموجة!",
        "game.next_wave_in": "الموجة التالية بعد {0} ثوانٍ.",
        "game.level_start": "§aبدء {0}!",
        "game.wave_approaching": "موجة جديدة من الزومبي تقترب!",
        "game.plant_unlocked": "§aلقد فتحت نباتًا جديدًا!",
        "game.collect_plant_prompt": "§eاجمع {0} للمتابعة.",
        "game.level_complete": "§a§lاكتمل المستوى!",
        "game.game_over": "§c§lانتهت اللعبة",
        "game.win_message": "§aلقد نجوت من كل الموجات!",
        "game.lose_message": "§cوصل الزومبي إلى منزلك!",
        "plant.on_cooldown": "§c{0} في فترة تهدئة لمدة {1} ثانية.",
        "plant.not_enough_pollen": "§cلا يوجد ما يكفي من حبوب اللقاح! {0} يكلف {1}.",
        "plant.invalid_surface": "§cيجب أن تزرع على سطح به أساس من كتلة ذهبية أو حديدية!",
        "plant.no_foundation": "§cتعذر العثور على أساس كامل بحجم 3x2 من نفس نوع الكتلة!",
        "plant.space_occupied": "§cلا يمكنك الزراعة هنا، المكان مشغول بنبات آخر!",
        "reset.confirm.title": "§cتأكيد إعادة التعيين",
        "reset.confirm.body": "§4هل أنت متأكد من أنك تريد إعادة تعيين كل تقدم المستوى؟ لا يمكن التراجع عن هذا الإجراء.",
        "reset.confirm.yes": "§cنعم، أعد تعيين التقدم",
        "reset.confirm.no": "§aلا، إلغاء",
        "reset.success": "§eتمت إعادة تعيين كل تقدم المستوى.",
        "reset.cancelled": "§aتم إلغاء إعادة تعيين التقدم.",
        "shop.title": "متجر النباتات",
        "shop.body": "حبوب اللقاح لديك: §e{0}",
        "shop.item_button": "{0}\n§eالتكلفة: {1}",
        "shop.purchase_success": "§aلقد اشتريت {0}!",
        "shop.not_enough_pollen": "§cليس لديك ما يكفي من حبوب اللقاح لشراء ذلك!",
        "tutorial.welcome.title": "§eمرحبًا بك في البرنامج التعليمي!",
        "tutorial.welcome.subtitle": "لنتعلم الأساسيات.",
        "tutorial.task.collect_first_pollen": "§aالمهمة: اجمع شمسك الأولى!\n§7انظر إلى الشمس وحرك ذراعك لجمعها،\nأو امش نحوها.",
        "tutorial.task.collect_for_peashooter": "§aالمهمة: اجمع ما يكفي من الشمس لشراء قاذف البازلاء!\n§7كل شمس تساوي 25 نقطة §e({0} / {1}§a)",
        "tutorial.task.place_first_peashooter": "§aالمهمة: ازرع أول قاذف بازلاء!\n§7أمسك عنصر قاذف البازلاء في يدك،\nانظر إلى مربع صالح واستخدم العنصر لزرعه.",
        "tutorial.task.collect_for_second": "§aالمهمة: رائع! اجمع ما يكفي لنبات ثان. (§e{0} / {1}§a)",
        "tutorial.task.place_second_peashooter": "§aالمهمة: ازرع قاذف البازلاء الثاني للبدء!",
        "tutorial.complete.title": "§aاكتمل البرنامج التعليمي!",
        "tutorial.complete.subtitle": "استعد للزومبي!",
        "entity.crazy_steve.name": "كريزي ديف",
        "dialogue.crazy_steve.1": "وابي-وابو!",
        "dialogue.crazy_steve.2": "هل رأيت مقلاتي المحظوظة؟\nأرتديها على رأسي!",
        "dialogue.crazy_steve.3": "الزومبي قادمون! بسرعة،\nأحضر... الشيء!",
        "dialogue.crazy_steve.4": "هل تعلم أن التاكو هو\nأفضل طعام للدماغ؟ لهذا\nأنا ذكي جدًا!",
        "dialogue.crazy_steve.5": "أنا لست مجنونًا، واقعي\nمختلف عن واقعك.",
        "dialogue.crazy_steve.6": "إذا أكل زومبي مهرجًا،\nهل يكون طعمه مضحكًا؟",
        "dialogue.crazy_steve.7": "نباتي المفضل هو...\nاللامع!",
        "dialogue.crazy_steve.8": "حاولت مرة أن أتفاهم\nمع زومبي. كان رأسه\nمن حجر.",
        "dialogue.crazy_steve.9": "حان وقت بدء الحفلة!\nمع... النباتات!",
        "dialogue.crazy_steve.10": "لأنني مجنوووون!",
        "dialogue.crazy_steve.11": "أنا أضع 'المرح'\nفي 'الفطر'!",
        "dialogue.crazy_steve.12": "قلت لعرستي 'ابتعدي عن\nالزومبي!'... لم تستمع.",
        "level.1.name": "المستوى 1: تعليمي",
        "level.1.wave.1": "الموجة 1",
        "level.1.wave.2": "الموجة الأخيرة",
        "level.1.unlock": "دوار الشمس",
        "level.2.name": "المستوى 2: الحديقة الأكبر",
        "level.2.wave.1": "الموجة 1",
        "level.2.wave.2": "الموجة الأخيرة",
        "level.2.unlock": "قنبلة الكرز",
        "level.3.name": "المستوى 3: شجار ذوي الأقماع",
        "level.3.wave.1": "الموجة 1",
        "level.3.wave.2": "الموجة الأخيرة",
        "level.3.unlock": "الجوزة",
        "level.4.name": "المستوى 4: لواء الدلاء",
        "level.4.wave.1": "الموجة 1",
        "level.4.wave.2": "الموجة 2",
        "level.4.wave.3": "الموجة الأخيرة",
        "level.4.unlock": "لغم البطاطس",
        "level.5.name": "المستوى 5: قوة البطاطس",
        "level.5.wave.1": "الموجة 1",
        "level.5.wave.2": "الموجة 2",
        "level.5.wave.3": "الموجة الأخيرة",
        "level.5.unlock": "بازلاء الثلج",
        "level.6.name": "المستوى 6: عودة ذوي الدلاء",
        "level.6.wave.1": "الموجة 1",
        "level.6.wave.2": "الموجة 2",
        "level.6.wave.3": "الموجة الأخيرة",
        "level.7.name": "المستوى 7: تسونامي الزومبي",
        "level.7.wave.1": "الموجة 1",
        "level.7.wave.2": "الموجة 2",
        "level.7.wave.3": "الموجة الأخيرة",
        "level.8.name": "المستوى 8: الموقف الأخير",
        "level.8.wave.1": "الموجة 1",
        "level.8.wave.2": "الموجة 2",
        "level.8.wave.3": "الموجة الأخيرة",
        "plant.sunflower.name": "دوار الشمس",
        "plant.peashooter.name": "قاذف البازلاء",
        "plant.cherry_bomb.name": "قنبلة الكرز",
        "plant.wallnut.name": "الجوزة",
        "plant.potato_mine.name": "لغم البطاطس",
        "plant.snow_pea.name": "بازلاء الثلج",
        "plant.big_walnut.name": "جوزة كبيرة",
    },
    // Indonesian (id)
    id: {
        "language.name": "Indonesia",
        "menu.title": "Menu Game",
        "menu.body": "Pilih kategori untuk memulai!",
        "menu.category.levels": "Level",
        "menu.category.shop": "Toko",
        "menu.category.settings": "Pengaturan",
        "menu.level": "Level {0}",
        "menu.shop.button": "     Toko\n(Segera Hadir)",
        "menu.settings.plant_health": "   Kesehatan\nTanaman: {0}",
        "menu.settings.zombie_health": "   Kesehatan\nZombie: {0}",
        "menu.settings.dialogue": " Dialog: {0}",
        "menu.settings.language": " Bahasa:\n {0}",
        "menu.settings.reset_progress": "§cSetel Ulang Semua\nProgres",
        "menu.shop.not_implemented": "§eToko belum diimplementasikan.",
        "menu.level.locked": "§cLevel ini terkunci! Selesaikan level sebelumnya untuk membuka.",
        "menu.level.in_progress": "§cSebuah level sudah sedang berlangsung! Anda tidak dapat memulai yang baru.",
        "misc.on": "§aNyala",
        "misc.off": "§cMati",
        "misc.interact_prompt": "§eBicaralah dengan Crazy Dave untuk memulai!",
        "game.title": "§2T§aa§2n§aa§2m§aa§2n §6VS §7Z§8o§7m§8b§7i",
        "game.sun_counter": "§eMatahari: {0}",
        "game.plant_cooldown": "§7{0}: {1}d",
        "game.wave_cleared": "§6Gelombang Selesai!",
        "game.next_wave_in": "Gelombang berikutnya dalam {0} detik.",
        "game.level_start": "§aMemulai {0}!",
        "game.wave_approaching": "Gelombang baru zombie mendekat!",
        "game.plant_unlocked": "§aAnda telah membuka tanaman baru!",
        "game.collect_plant_prompt": "§eKumpulkan {0} untuk melanjutkan.",
        "game.level_complete": "§a§lLEVEL SELESAI!",
        "game.game_over": "§c§lPERMAINAN BERAKHIR",
        "game.win_message": "§aAnda selamat dari semua gelombang!",
        "game.lose_message": "§cZombie mencapai rumah Anda!",
        "plant.on_cooldown": "§c{0} sedang cooldown selama {1}d.",
        "plant.not_enough_pollen": "§cSerbuk sari tidak cukup! {0} berharga {1}.",
        "plant.invalid_surface": "§cAnda harus menanam di permukaan dengan fondasi balok emas atau besi!",
        "plant.no_foundation": "§cTidak dapat menemukan fondasi 3x2 lengkap dari tipe balok yang sama!",
        "plant.space_occupied": "§cAnda tidak bisa menanam di sini, tempat ini sudah ditempati tanaman lain!",
        "reset.confirm.title": "§cKonfirmasi Setel Ulang",
        "reset.confirm.body": "§4Apakah Anda yakin ingin menyetel ulang semua progres level? Tindakan ini tidak dapat dibatalkan.",
        "reset.confirm.yes": "§cYa, Setel Ulang Progres",
        "reset.confirm.no": "§aTidak, Batal",
        "reset.success": "§eSemua progres level telah disetel ulang.",
        "reset.cancelled": "§aPenyetelan ulang progres dibatalkan.",
        "shop.title": "Toko Tanaman",
        "shop.body": "Serbuk Sari Anda: §e{0}",
        "shop.item_button": "{0}\n§eHarga: {1}",
        "shop.purchase_success": "§aAnda membeli {0}!",
        "shop.not_enough_pollen": "§cAnda tidak punya cukup serbuk sari untuk membeli itu!",
        "tutorial.welcome.title": "§eSelamat Datang di Tutorial!",
        "tutorial.welcome.subtitle": "Mari pelajari dasarnya.",
        "tutorial.task.collect_first_pollen": "§aTugas: Kumpulkan matahari pertamamu!\n§7Lihat matahari dan ayunkan lenganmu untuk mengumpulkannya,\natau dekati.",
        "tutorial.task.collect_for_peashooter": "§aTugas: Kumpulkan matahari yang cukup untuk membeli Peashooter!\n§7Setiap matahari bernilai 25 poin §e({0} / {1}§a)",
        "tutorial.task.place_first_peashooter": "§aTugas: Tanam Peashooter pertamamu!\n§7Pegang item Peashooter di tanganmu,\nlihat petak yang valid, dan gunakan item untuk menanamnya.",
        "tutorial.task.collect_for_second": "§aTugas: Bagus! Kumpulkan cukup untuk tanaman kedua. (§e{0} / {1}§a)",
        "tutorial.task.place_second_peashooter": "§aTugas: Tanam Peashooter keduamu untuk memulai!",
        "tutorial.complete.title": "§aTutorial Selesai!",
        "tutorial.complete.subtitle": "Bersiaplah untuk para zombie!",
        "entity.crazy_steve.name": "Crazy Dave",
        "dialogue.crazy_steve.1": "Wabby-wabbo!",
        "dialogue.crazy_steve.2": "Pernah lihat panci keberuntunganku?\nAku pakai di kepala!",
        "dialogue.crazy_steve.3": "Zombi datang! Cepat,\nambil... uh... itu tuh!",
        "dialogue.crazy_steve.4": "Tahu tidak, taco itu\nmakanan otak terbaik? Makanya\naku pintar sekali!",
        "dialogue.crazy_steve.5": "Aku tidak gila, realitasku\nhanya berbeda darimu.",
        "dialogue.crazy_steve.6": "Kalau zombi makan badut,\nrasanya lucu tidak ya?",
        "dialogue.crazy_steve.7": "Tanaman favoritku itu yang...\nyang berkilau!",
        "dialogue.crazy_steve.8": "Dulu aku coba bicara\ndengan zombi. Dia agak\nkeras kepala.",
        "dialogue.crazy_steve.9": "Waktunya mulai pesta!\nDengan... tanaman!",
        "dialogue.crazy_steve.10": "Karena aku GIIIIILA!",
        "dialogue.crazy_steve.11": "Aku menaruh 'senang'\ndi 'jamur'!",
        "dialogue.crazy_steve.12": "Aku bilang ke rumputku\n'jangan injak zombiku!'...\nDia tidak dengar.",
        "level.1.name": "Level 1: Tutorial",
        "level.1.wave.1": "Gelombang 1",
        "level.1.wave.2": "Gelombang Terakhir",
        "level.1.unlock": "Bunga Matahari",
        "level.2.name": "Level 2: Halaman yang Lebih Besar",
        "level.2.wave.1": "Gelombang 1",
        "level.2.wave.2": "Gelombang Terakhir",
        "level.2.unlock": "Bom Ceri",
        "level.3.name": "Level 3: Keributan Conehead",
        "level.3.wave.1": "Gelombang 1",
        "level.3.wave.2": "Gelombang Terakhir",
        "level.3.unlock": "Wall-nut",
        "level.4.name": "Level 4: Brigade Buckethead",
        "level.4.wave.1": "Gelombang 1",
        "level.4.wave.2": "Gelombang 2",
        "level.4.wave.3": "Gelombang Terakhir",
        "level.4.unlock": "Ranjau Kentang",
        "level.5.name": "Level 5: Kekuatan Kentang",
        "level.5.wave.1": "Gelombang 1",
        "level.5.wave.2": "Gelombang 2",
        "level.5.wave.3": "Gelombang Terakhir",
        "level.5.unlock": "Snow Pea",
        "level.6.name": "Level 6: Para Buckethead Kembali",
        "level.6.wave.1": "Gelombang 1",
        "level.6.wave.2": "Gelombang 2",
        "level.6.wave.3": "Gelombang Terakhir",
        "level.7.name": "Level 7: Tsunami Zombie",
        "level.7.wave.1": "Gelombang 1",
        "level.7.wave.2": "Gelombang 2",
        "level.7.wave.3": "Gelombang Terakhir",
        "level.8.name": "Level 8: Pertahanan Terakhir",
        "level.8.wave.1": "Gelombang 1",
        "level.8.wave.2": "Gelombang 2",
        "level.8.wave.3": "Gelombang Terakhir",
        "plant.sunflower.name": "Bunga Matahari",
        "plant.peashooter.name": "Peashooter",
        "plant.cherry_bomb.name": "Bom Ceri",
        "plant.wallnut.name": "Wall-nut",
        "plant.potato_mine.name": "Ranjau Kentang",
        "plant.snow_pea.name": "Snow Pea",
        "plant.big_walnut.name": "Walnut Besar",
    },
    // Mandarin (zh)
    zh: {
        "language.name": "中文",
        "menu.title": "游戏菜单",
        "menu.body": "选择一个类别开始！",
        "menu.category.levels": "关卡",
        "menu.category.shop": "商店",
        "menu.category.settings": "设置",
        "menu.level": "第 {0} 关",
        "menu.shop.button": "     商店\n(即将推出)",
        "menu.settings.plant_health": "   植物\n生命值: {0}",
        "menu.settings.zombie_health": "   僵尸\n生命值: {0}",
        "menu.settings.dialogue": " 对话: {0}",
        "menu.settings.language": " 语言:\n {0}",
        "menu.settings.reset_progress": "§c重置所有\n进度",
        "menu.shop.not_implemented": "§e商店尚未实施。",
        "menu.level.locked": "§c此关卡已锁定！完成前一关卡以解锁。",
        "menu.level.in_progress": "§c一个关卡已在进行中！您无法开始新的关卡。",
        "misc.on": "§a开",
        "misc.off": "§c关",
        "misc.interact_prompt": "§e和疯狂的戴夫交谈以开始！",
        "game.title": "§2植§a物§2大§a战§2僵§a尸",
        "game.sun_counter": "§e阳光: {0}",
        "game.plant_cooldown": "§7{0}: {1}秒",
        "game.wave_cleared": "§6一波已清除！",
        "game.next_wave_in": "下一波在 {0} 秒后。",
        "game.level_start": "§a开始 {0}!",
        "game.wave_approaching": "一大波僵尸正在接近！",
        "game.plant_unlocked": "§a你解锁了一个新植物！",
        "game.collect_plant_prompt": "§e收集 {0} 以继续。",
        "game.level_complete": "§a§l关卡完成！",
        "game.game_over": "§c§l游戏结束",
        "game.win_message": "§a你成功抵御了所有僵尸！",
        "game.lose_message": "§c僵尸吃掉了你的脑子！",
        "plant.on_cooldown": "§c{0} 冷却中，剩余 {1} 秒。",
        "plant.not_enough_pollen": "§c阳光不足！{0} 需要 {1}。",
        "plant.invalid_surface": "§c你必须种植在有金块或铁块地基的表面上！",
        "plant.no_foundation": "§c找不到一个完整的 3x2 同类型方块地基！",
        "plant.space_occupied": "§c你不能在这里种植，这个地方已经被其他植物占据了！",
        "reset.confirm.title": "§c确认重置",
        "reset.confirm.body": "§4你确定要重置所有关卡进度吗？此操作无法撤销。",
        "reset.confirm.yes": "§c是，重置进度",
        "reset.confirm.no": "§a否，取消",
        "reset.success": "§e所有关卡进度已重置。",
        "reset.cancelled": "§a进度重置已取消。",
        "shop.title": "植物商店",
        "shop.body": "你的阳光: §e{0}",
        "shop.item_button": "{0}\n§e价格: {1}",
        "shop.purchase_success": "§a你购买了 {0}!",
        "shop.not_enough_pollen": "§c你没有足够的阳光购买！",
        "tutorial.welcome.title": "§e欢迎来到教程！",
        "tutorial.welcome.subtitle": "让我们学习基础知识。",
        "tutorial.task.collect_first_pollen": "§a任务：收集你的第一个阳光！\n§7看着阳光并挥动你的手臂来收集它，\n或者走到它旁边。",
        "tutorial.task.collect_for_peashooter": "§a任务：收集足够的阳光来购买一个豌豆射手！\n§7每个阳光价值25点 §e({0} / {1}§a)",
        "tutorial.task.place_first_peashooter": "§a任务：种植你的第一个豌豆射手！\n§7手里拿着豌豆射手物品，\n看着一个有效的地块，然后使用物品来种植它。",
        "tutorial.task.collect_for_second": "§a任务：太棒了！收集足够的阳光来种植第二个植物。（§e{0} / {1}§a）",
        "tutorial.task.place_second_peashooter": "§a任务：种植你的第二个豌豆射手以开始！",
        "tutorial.complete.title": "§a教程完成！",
        "tutorial.complete.subtitle": "准备好迎接僵尸吧！",
        "entity.crazy_steve.name": "疯狂的戴夫",
        "dialogue.crazy_steve.1": "哇比哇啵！",
        "dialogue.crazy_steve.2": "你看到我的幸运平底锅了吗？\n我把它戴在头上！",
        "dialogue.crazy_steve.3": "僵尸来了！快，\n抓住那个……嗯……那个东西！",
        "dialogue.crazy_steve.4": "你知道吗？玉米饼是\n最好的健脑食品！所以\n我才这么聪明！",
        "dialogue.crazy_steve.5": "我没疯，只是我的现实\n和你的不一样。",
        "dialogue.crazy_steve.6": "如果僵尸吃了小丑，\n味道会很滑稽吗？",
        "dialogue.crazy_steve.7": "我最喜欢的植物是……\n那个闪闪发光的！",
        "dialogue.crazy_steve.8": "我曾经试着和僵尸讲道理。\n他有点……脑子不灵光。",
        "dialogue.crazy_steve.9": "是时候开始派对了！\n用……植物！",
        "dialogue.crazy_steve.10": "因为我太疯狂啦！",
        "dialogue.crazy_steve.11": "我把“乐趣”放进了\n“真菌”里！",
        "dialogue.crazy_steve.12": "我告诉我的草坪\n“离我的僵尸远点！”……\n它不听。",
        "level.1.name": "第1关：教程",
        "level.1.wave.1": "第一波",
        "level.1.wave.2": "最后一波",
        "level.1.unlock": "向日葵",
        "level.2.name": "第2关：更大的草坪",
        "level.2.wave.1": "第一波",
        "level.2.wave.2": "最后一波",
        "level.2.unlock": "樱桃炸弹",
        "level.3.name": "第3关：路障僵尸的混乱",
        "level.3.wave.1": "第一波",
        "level.3.wave.2": "最后一波",
        "level.3.unlock": "坚果墙",
        "level.4.name": "第4关：铁桶僵尸军团",
        "level.4.wave.1": "第一波",
        "level.4.wave.2": "第二波",
        "level.4.wave.3": "最后一波",
        "level.4.unlock": "土豆地雷",
        "level.5.name": "第5关：土豆的力量",
        "level.5.wave.1": "第一波",
        "level.5.wave.2": "第二波",
        "level.5.wave.3": "最后一波",
        "level.5.unlock": "寒冰射手",
        "level.6.name": "第6关：铁桶僵尸回来了",
        "level.6.wave.1": "第一波",
        "level.6.wave.2": "第二波",
        "level.6.wave.3": "最后一波",
        "level.7.name": "第7关：僵尸海啸",
        "level.7.wave.1": "第一波",
        "level.7.wave.2": "第二波",
        "level.7.wave.3": "最后一波",
        "level.8.name": "第8关：最后的阵地",
        "level.8.wave.1": "第一波",
        "level.8.wave.2": "第二波",
        "level.8.wave.3": "最后一波",
        "plant.sunflower.name": "向日葵",
        "plant.peashooter.name": "豌豆射手",
        "plant.cherry_bomb.name": "樱桃炸弹",
        "plant.wallnut.name": "坚果墙",
        "plant.potato_mine.name": "土豆地雷",
        "plant.snow_pea.name": "寒冰射手",
        "plant.big_walnut.name": "大坚果",
    },
    // Portuguese (pt)
    pt: {
        "language.name": "Português",
        "menu.title": "Menu do Jogo",
        "menu.body": "Selecione uma categoria para começar!",
        "menu.category.levels": "Níveis",
        "menu.category.shop": "Loja",
        "menu.category.settings": "Configurações",
        "menu.level": "Nível {0}",
        "menu.shop.button": "     Loja\n(Em Breve)",
        "menu.settings.plant_health": "   Vida da\nPlanta: {0}",
        "menu.settings.zombie_health": "   Vida do\nZumbi: {0}",
        "menu.settings.dialogue": " Diálogo: {0}",
        "menu.settings.language": " Idioma:\n {0}",
        "menu.settings.reset_progress": "§cRedefinir Todo\no Progresso",
        "menu.shop.not_implemented": "§eA Loja ainda não foi implementada.",
        "menu.level.locked": "§cEste nível está bloqueado! Complete o nível anterior para desbloquear.",
        "menu.level.in_progress": "§cUm nível já está em andamento! Você não pode iniciar um novo.",
        "misc.on": "§aLigado",
        "misc.off": "§cDesligado",
        "misc.interact_prompt": "§eFale com o Dave Doidão para começar!",
        "game.title": "§2P§al§2a§an§2t§as §6VS §7Z§8u§7m§8b§7i§8s",
        "game.sun_counter": "§eSol: {0}",
        "game.plant_cooldown": "§7{0}: {1}s",
        "game.wave_cleared": "§6Onda Concluída!",
        "game.next_wave_in": "Próxima onda em {0} segundos.",
        "game.level_start": "§aIniciando {0}!",
        "game.wave_approaching": "Uma nova onda de zumbis está se aproximando!",
        "game.plant_unlocked": "§aVocê desbloqueou uma nova planta!",
        "game.collect_plant_prompt": "§eColete a {0} para continuar.",
        "game.level_complete": "§a§lNÍVEL COMPLETO!",
        "game.game_over": "§c§lFIM DE JOGO",
        "game.win_message": "§aVocê sobreviveu a todas as ondas!",
        "game.lose_message": "§cOs zumbis chegaram à sua casa!",
        "plant.on_cooldown": "§c{0} está em recarga por {1}s.",
        "plant.not_enough_pollen": "§cSol insuficiente! {0} custa {1}.",
        "plant.invalid_surface": "§cVocê deve plantar em uma superfície com uma base de bloco de ouro ou ferro!",
        "plant.no_foundation": "§cNão foi possível encontrar uma base 3x2 completa do mesmo tipo de bloco!",
        "plant.space_occupied": "§cVocê não pode plantar aqui, o espaço está ocupado por outra planta!",
        "reset.confirm.title": "§cConfirmar Redefinição",
        "reset.confirm.body": "§4Tem certeza de que deseja redefinir todo o progresso do nível? Esta ação não pode ser desfeita.",
        "reset.confirm.yes": "§cSim, Redefinir Progresso",
        "reset.confirm.no": "§aNão, Cancelar",
        "reset.success": "§eTodo o progresso do nível foi redefinido.",
        "reset.cancelled": "§aRedefinição de progresso cancelada.",
        "shop.title": "Loja de Plantas",
        "shop.body": "Seu Sol: §e{0}",
        "shop.item_button": "{0}\n§eCusto: {1}",
        "shop.purchase_success": "§aVocê comprou uma {0}!",
        "shop.not_enough_pollen": "§cVocê não tem sol suficiente para comprar isso!",
        "tutorial.welcome.title": "§eBem-vindo ao Tutorial!",
        "tutorial.welcome.subtitle": "Vamos aprender o básico.",
        "tutorial.task.collect_first_pollen": "§aTarefa: Colete seu primeiro sol!\n§7Olhe para o sol e balance seu braço para coletá-lo,\nou caminhe até ele.",
        "tutorial.task.collect_for_peashooter": "§aTarefa: Colete sol suficiente para comprar uma Disparervilha!\n§7Cada sol vale 25 pontos §e({0} / {1}§a)",
        "tutorial.task.place_first_peashooter": "§aTarefa: Plante sua primeira Disparervilha!\n§7Segure o item Disparervilha em sua mão,\nolhe para um ladrilho válido e use o item para plantá-lo.",
        "tutorial.task.collect_for_second": "§aTarefa: Ótimo! Colete o suficiente para uma segunda planta. (§e{0} / {1}§a)",
        "tutorial.task.place_second_peashooter": "§aTarefa: Plante sua segunda Disparervilha para começar!",
        "tutorial.complete.title": "§aTutorial Concluído!",
        "tutorial.complete.subtitle": "Prepare-se para os zumbis!",
        "entity.crazy_steve.name": "Dave Doidão",
        "dialogue.crazy_steve.1": "Wabby-wabbo!",
        "dialogue.crazy_steve.2": "Você viu minha\npanela da sorte? Eu uso\nna cabeça!",
        "dialogue.crazy_steve.3": "Os zumbis estão vindo! Rápido,\npegue o... uh... o treco!",
        "dialogue.crazy_steve.4": "Você sabia que tacos são\na melhor comida para o cérebro? É por\nisso que sou tão esperto!",
        "dialogue.crazy_steve.5": "Eu não sou louco, minha realidade\né apenas diferente da sua.",
        "dialogue.crazy_steve.6": "Se um zumbi come um\npalhaço, o gosto é engraçado?",
        "dialogue.crazy_steve.7": "Minha planta favorita é a...\nbrilhante!",
        "dialogue.crazy_steve.8": "Uma vez tentei argumentar\ncom um zumbi. Ele era meio\ncabeça-dura.",
        "dialogue.crazy_steve.9": "Hora de começar esta festa!\nCom... plantas!",
        "dialogue.crazy_steve.10": "Porque eu sou DOIDÃÃÃÃO!",
        "dialogue.crazy_steve.11": "Eu coloco o 'divertido'\nem 'fungo'!",
        "dialogue.crazy_steve.12": "Eu disse para o meu gramado\n'saia dos meus zumbis!'... Ele\nnão ouviu.",
        "level.1.name": "Nível 1: Tutorial",
        "level.1.wave.1": "Onda 1",
        "level.1.wave.2": "Onda Final",
        "level.1.unlock": "Girassol",
        "level.2.name": "Nível 2: O Gramado Maior",
        "level.2.wave.1": "Onda 1",
        "level.2.wave.2": "Onda Final",
        "level.2.unlock": "Cereja Explosiva",
        "level.3.name": "Nível 3: Confusão de Cones",
        "level.3.wave.1": "Onda 1",
        "level.3.wave.2": "Onda Final",
        "level.3.unlock": "Noz-obstáculo",
        "level.4.name": "Nível 4: Brigada dos Baldes",
        "level.4.wave.1": "Onda 1",
        "level.4.wave.2": "Onda 2",
        "level.4.wave.3": "Onda Final",
        "level.4.unlock": "Batata-mina",
        "level.5.name": "Nível 5: Poder da Batata",
        "level.5.wave.1": "Onda 1",
        "level.5.wave.2": "Onda 2",
        "level.5.wave.3": "Onda Final",
        "level.5.unlock": "Disparervilha de Gelo",
        "level.6.name": "Nível 6: Os Cabeças de Balde Voltaram",
        "level.6.wave.1": "Onda 1",
        "level.6.wave.2": "Onda 2",
        "level.6.wave.3": "Onda Final",
        "level.7.name": "Nível 7: Tsunami de Zumbis",
        "level.7.wave.1": "Onda 1",
        "level.7.wave.2": "Onda 2",
        "level.7.wave.3": "Onda Final",
        "level.8.name": "Nível 8: A Batalha Final",
        "level.8.wave.1": "Onda 1",
        "level.8.wave.2": "Onda 2",
        "level.8.wave.3": "Onda Final",
        "plant.sunflower.name": "Girassol",
        "plant.peashooter.name": "Disparervilha",
        "plant.cherry_bomb.name": "Cereja Explosiva",
        "plant.wallnut.name": "Noz-obstáculo",
        "plant.potato_mine.name": "Batata-mina",
        "plant.snow_pea.name": "Disparervilha de Gelo",
        "plant.big_walnut.name": "Noz-obstáculo Grande",
    },
};

export class LanguageManager {
    /**
     * Gets the player's currently selected language.
     * @param {import("@minecraft/server").Player | import("@minecraft/server").Entity} target The player or entity.
     * @returns {string} The language code (e.g., 'en', 'es').
     */
    static getLanguage(target) {
        return target.getDynamicProperty(LANGUAGE_KEY) ?? 'en';
    }

    /**
     * Sets the player's language.
     * @param {import("@minecraft/server").Player} player The player.
     * @param {string} langCode The language code to set.
     */
    static setLanguage(player, langCode) {
        if (translations[langCode]) {
            player.setDynamicProperty(LANGUAGE_KEY, langCode);
        } else {
            console.warn(`[LanguageManager] Attempted to set an invalid language: ${langCode}`);
        }
    }

    /**
     * Gets a translated string for the player's language.
     * @param {import("@minecraft/server").Player | import("@minecraft/server").Entity} target The player or entity.
     * @param {string} key The key of the string to translate.
     * @param {Array<string|number>} args Arguments to insert into the string.
     * @returns {string} The translated and formatted string.
     */
    static get(target, key, ...args) {
        const langCode = this.getLanguage(target);
        const langTranslations = translations[langCode] || translations.en;
        let text = langTranslations[key] || translations.en[key] || key;

        if (args.length > 0) {
            for (let i = 0; i < args.length; i++) {
                text = text.replace(`{${i}}`, args[i]);
            }
        }
        return text;
    }

    /**
     * Gets all translation keys that start with a specific prefix.
     * @param {string} prefix The prefix to search for.
     * @param {string} langCode The language code to search in.
     * @returns {string[]} An array of matching keys.
     */
    static getKeysWithPrefix(prefix, langCode = 'en') {
        const langTranslations = translations[langCode] || translations.en;
        return Object.keys(langTranslations).filter(key => key.startsWith(prefix));
    }

    /**
     * Gets a list of all available languages.
     * @returns {Array<{code: string, name: string}>}
     */
    static getAvailableLanguages() {
        return Object.keys(translations).map(code => ({
            code: code,
            name: translations[code]["language.name"]
        }));
    }
}
